spring:
  application:
    name: mscoletas
  datasource:
    url: jdbc:mysql://localhost:3306/healthflow_coleta
    username: root
    password: root123
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate:
        format_sql:true
  kafka:
    bootstrap-servers: 'localhost:29092'
    consumer:
      group-id: healthflow-atualizacao-coleta
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value} }
    prefer-ip-address: true
    ip-address: 127.0.0.1


server:
  port: 8082


healthflow:
  coletas:
    clients:
      produtos:
        url: 'http://localhost:8080/produtos'
      clientes:
        url: 'http://localhost:8080/clientes'
  config:
    kafka:
      server-url: 'localhost:29092'
      topics:
        pedidos-pagos: 'health_flow.pedidos-pagos'
        exames-faturados: 'health_flow.exames-faturados'
        exames-prontos: 'health_flow.exames-prontos'