version: '3.9'

services:

  minio:
    image: quay.io/minio/minio:RELEASE.2025-09-07T16-13-09Z-cpuv1
    ports:
      - "9000:9000" #API
      - "9001:9001" #CONSOLE WEB
    volumes:
      - ./docs:/data
    environment:
      MINIO_ROOT_USER: "minio-admin"
      MINIO_ROOT_PASSWORD: "admin-123"
    command: server /data --console-address ":9001"
    restart: unless-stopped