spring:
  application:
    name: msfaturamento
  kafka:
    bootstrap-servers: 'localhost:29092'
    consumer:
      group-id: healthflow-faturamento
      auto-offset-reset: earliest

healthflow:
  config:
    kafka:
      topics:
        pedidos-pagos: 'health_flow.pedidos-pagos'

server:
  port: 8084

minio:
  url: 'http://localhost:9000'
  access-key: minio-admin
  secret-key: admin-123
  bucket-name: healthflow.faturas


